In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

df = pd.read_csv("order_items.csv")

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully
Rows: 20000
Columns: 9

In [3]:
df_original = df.copy()

print("Original backup created successfully")
print("Backup rows:", df_original.shape[0])
print("Backup columns:", df_original.shape[1])

Original backup created successfully
Backup rows: 20000
Backup columns: 9

In [4]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nDataset information:")
df.info()

Column names:
['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_percentage', 'item_revenue', 'item_cost', 'profit']

First 5 rows:

,order_item_id,order_id,product_id,quantity,unit_price,discount_percentage,item_revenue,item_cost,profit
0,OI10000007,ORD1000002,PROD10470,2,590.0,30.0,826.0,712.38,113.62
1,OI10000021,ORD1000009,PROD10073,2,1360.0,23.0,2094.4,1953.58,140.82
2,OI10000035,ORD1000014,PROD10101,2,780.0,15.0,1326.0,1119.32,206.68
3,OI10000051,ORD1000020,PROD10403,3,2030.0,5.0,5785.5,3578.40,2207.10
4,OI10000055,ORD1000022,PROD10392,3,8430.0,3.0,24531.3,17520.06,7011.24

Last 5 rows:

,order_item_id,order_id,product_id,quantity,unit_price,discount_percentage,item_revenue,item_cost,profit
19995,OI10254252,ORD1099972,PROD10404,2,4380.0,18.0,7183.2,5141.92,2041.28
19996,OI10254258,ORD1099974,PROD10064,2,2830.0,31.5,3877.1,4078.96,-201.86
19997,OI10254269,ORD1099978,PROD10258,4,1500.0,0.0,6000.0,3947.04,2052.96
19998,OI10254270,ORD1099979,PROD10403,1,2030.0,3.0,1969.1,1192.80,776.30
19999,OI10254271,ORD1099980,PROD10482,1,200.0,30.0,140.0,154.98,-14.98

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_item_id        20000 non-null  str
 1   order_id             20000 non-null  str
 2   product_id           20000 non-null  str
 3   quantity             20000 non-null  int64
 4   unit_price           20000 non-null  float64
 5   discount_percentage  20000 non-null  float64
 6   item_revenue         20000 non-null  float64
 7   item_cost            20000 non-null  float64
 8   profit               20000 non-null  float64
dtypes: float64(5), int64(1), str(3)
memory usage: 1.9 MB

In [5]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (
        df.isna().sum() / len(df) * 100
    ).round(2)
})

missing_report

                     Missing_Count  Missing_Percentage
order_item_id                    0                 0.0
order_id                         0                 0.0
product_id                       0                 0.0
quantity                         0                 0.0
unit_price                       0                 0.0
discount_percentage              0                 0.0
item_revenue                     0                 0.0
item_cost                        0                 0.0
profit                           0                 0.0

In [6]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [7]:
for col in ["order_item_id", "order_id", "product_id"]:
    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("=" * 50)

    print("Missing:", df[col].isna().sum())
    print("Unique:", df[col].nunique(dropna=True))
    print("Repeated values:", df[col].duplicated().sum())

==================================================
COLUMN: order_item_id
==================================================
Missing: 0
Unique: 20000
Repeated values: 0

==================================================
COLUMN: order_id
==================================================
Missing: 0
Unique: 20000
Repeated values: 0

==================================================
COLUMN: product_id
==================================================
Missing: 0
Unique: 546
Repeated values: 19454

In [8]:
invalid_order_item_ids = ~df["order_item_id"].str.startswith("ITEM", na=False)
invalid_order_ids = ~df["order_id"].str.startswith("ORD", na=False)
invalid_product_ids = ~df["product_id"].str.startswith("PROD", na=False)

print("Invalid order_item_id format:", invalid_order_item_ids.sum())
print("Invalid order_id format:", invalid_order_ids.sum())
print("Invalid product_id format:", invalid_product_ids.sum())

Invalid order_item_id format: 20000
Invalid order_id format: 0
Invalid product_id format: 0

In [9]:
print("First 20 order_item_id values:")
print(df["order_item_id"].head(20).tolist())

print("\nSample unique order_item_id values:")
print(df["order_item_id"].drop_duplicates().head(20).tolist())

First 20 order_item_id values:
['OI10000007', 'OI10000021', 'OI10000035', 'OI10000051', 'OI10000055', 'OI10000056', 'OI10000057', 'OI10000077', 'OI10000093', 'OI10000106', 'OI10000184', 'OI10000185', 'OI10000188', 'OI10000192', 'OI10000193', 'OI10000216', 'OI10000221', 'OI10000235', 'OI10000265', 'OI10000273']

Sample unique order_item_id values:
['OI10000007', 'OI10000021', 'OI10000035', 'OI10000051', 'OI10000055', 'OI10000056', 'OI10000057', 'OI10000077', 'OI10000093', 'OI10000106', 'OI10000184', 'OI10000185', 'OI10000188', 'OI10000192', 'OI10000193', 'OI10000216', 'OI10000221', 'OI10000235', 'OI10000265', 'OI10000273']

In [10]:
invalid_order_item_ids = ~df["order_item_id"].str.startswith("OI", na=False)

print("Invalid order_item_id format:", invalid_order_item_ids.sum())

Invalid order_item_id format: 0

In [11]:
numeric_columns = [
    "quantity",
    "unit_price",
    "discount_percentage",
    "item_revenue",
    "item_cost",
    "profit"
]

for col in numeric_columns:
    print(
        col,
        "→ Negative values:",
        (df[col] < 0).sum()
    )

quantity → Negative values: 0
unit_price → Negative values: 0
discount_percentage → Negative values: 0
item_revenue → Negative values: 0
item_cost → Negative values: 0
profit → Negative values: 2991

In [12]:
negative_profit = df[df["profit"] < 0]

print("Negative-profit rows:", len(negative_profit))

print("\nNegative-profit summary:")
display(
    negative_profit[
        [
            "quantity",
            "unit_price",
            "discount_percentage",
            "item_revenue",
            "item_cost",
            "profit"
        ]
    ].describe()
)

print("\nFirst 20 negative-profit records:")
display(
    negative_profit[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price",
            "discount_percentage",
            "item_revenue",
            "item_cost",
            "profit"
        ]
    ].head(20)
)

Negative-profit rows: 2991

Negative-profit summary:

,quantity,unit_price,discount_percentage,item_revenue,item_cost,profit
count,2991.000000,2991.000000,2991.000000,2991.000000,2991.000000,2991.000000
mean,2.346372,10861.695085,25.799398,19064.118689,21338.649766,-2274.531077
std,1.156508,18255.956727,5.610970,36675.620059,41135.305019,5581.975097
min,1.000000,50.000000,10.000000,33.500000,34.120000,-78804.800000
25%,1.000000,590.000000,21.500000,860.125000,910.420000,-1673.040000
50%,2.000000,2640.000000,26.500000,3960.000000,4565.100000,-292.400000
75%,3.000000,12420.000000,30.000000,18312.000000,20715.240000,-44.820000
max,7.000000,76020.000000,33.000000,380609.700000,398780.340000,-0.030000

First 20 negative-profit records:

,order_item_id,order_id,product_id,quantity,unit_price,discount_percentage,item_revenue,item_cost,profit
18,OI10000265,ORD1000107,PROD10374,3,930.0,30.0,1953.00,1980.63,-27.63
19,OI10000273,ORD1000110,PROD10117,4,1090.0,30.0,3052.00,3266.96,-214.96
29,OI10000399,ORD1000160,PROD10152,2,4110.0,30.0,5754.00,7507.52,-1753.52
35,OI10000476,ORD1000193,PROD10072,2,15460.0,18.0,25354.40,28203.74,-2849.34
49,OI10000606,ORD1000250,PROD10111,2,190.0,33.0,254.60,297.16,-42.56
72,OI10000960,ORD1000383,PROD10417,4,2640.0,25.0,7920.00,9130.20,-1210.20
83,OI10001055,ORD1000422,PROD10355,2,5880.0,20.0,9408.00,10357.62,-949.62
101,OI10001229,ORD1000494,PROD10376,1,5630.0,31.5,3856.55,4829.39,-972.84
104,OI10001288,ORD1000516,PROD10399,1,1790.0,20.0,1432.00,1503.90,-71.90
106,OI10001353,ORD1000537,PROD10101,2,780.0,30.0,1092.00,1119.32,-27.32
107,OI10001363,ORD1000541,PROD10541,3,150.0,25.0,337.50,353.34,-15.84
109,OI10001382,ORD1000549,PROD10092,1,920.0,33.0,616.40,762.38,-145.98
110,OI10001385,ORD1000551,PROD10518,1,1980.0,25.0,1485.00,1633.02,-148.02
114,OI10001411,ORD1000564,PROD10058,4,73700.0,21.5,231418.00,253999.56,-22581.56
119,OI10001540,ORD1000613,PROD10233,1,3440.0,30.0,2408.00,2676.46,-268.46
124,OI10001600,ORD1000637,PROD10018,2,210.0,25.0,315.00,320.14,-5.14
132,OI10001687,ORD1000669,PROD10014,3,50.0,25.0,112.50,130.29,-17.79
133,OI10001699,ORD1000675,PROD10203,2,12420.0,15.0,21114.00,21408.38,-294.38
141,OI10001823,ORD1000721,PROD10172,2,490.0,31.5,671.30,766.12,-94.82
147,OI10001935,ORD1000761,PROD10411,5,23190.0,31.5,79425.75,89460.10,-10034.35

In [13]:
calculated_profit = (
    df["item_revenue"] - df["item_cost"]
).round(2)

profit_difference = (
    df["profit"] - calculated_profit
).round(2)

print(
    "Rows matching profit formula:",
    (profit_difference == 0).sum()
)

print(
    "Rows with profit differences:",
    (profit_difference != 0).sum()
)

print(
    "Maximum profit difference:",
    profit_difference.abs().max()
)

Rows matching profit formula: 20000
Rows with profit differences: 0
Maximum profit difference: 0.0

In [14]:
invalid_discount = (
    (df["discount_percentage"] < 0) |
    (df["discount_percentage"] > 100)
)

print("Invalid discount values:", invalid_discount.sum())

Invalid discount values: 0

In [15]:
print("Minimum quantity:", df["quantity"].min())
print("Maximum quantity:", df["quantity"].max())
print("Zero quantity:", (df["quantity"] == 0).sum())
print("Negative quantity:", (df["quantity"] < 0).sum())

Minimum quantity: 1
Maximum quantity: 8
Zero quantity: 0
Negative quantity: 0

In [16]:
for col in ["unit_price", "item_revenue", "item_cost"]:
    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("=" * 50)
    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())
    print("Zero values:", (df[col] == 0).sum())
    print("Negative values:", (df[col] < 0).sum())

==================================================
COLUMN: unit_price
==================================================
Minimum: 50.0
Maximum: 76020.0
Zero values: 0
Negative values: 0

==================================================
COLUMN: item_revenue
==================================================
Minimum: 33.5
Maximum: 449278.2
Zero values: 0
Negative values: 0

==================================================
COLUMN: item_cost
==================================================
Minimum: 34.12
Maximum: 413849.76
Zero values: 0
Negative values: 0

In [17]:
calculated_revenue = (
    df["unit_price"]
    * df["quantity"]
    * (1 - df["discount_percentage"] / 100)
).round(2)

revenue_difference = (
    df["item_revenue"] - calculated_revenue
).round(2)

print(
    "Rows matching revenue formula:",
    (revenue_difference == 0).sum()
)

print(
    "Rows with revenue differences:",
    (revenue_difference != 0).sum()
)

print(
    "Maximum revenue difference:",
    revenue_difference.abs().max()
)

Rows matching revenue formula: 20000
Rows with revenue differences: 0
Maximum revenue difference: 0.0

In [18]:
outlier_columns = [
    "quantity",
    "unit_price",
    "discount_percentage",
    "item_revenue",
    "item_cost",
    "profit"
]

for col in outlier_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = (
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    )

    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)
    print("Potential Outliers:", outliers.sum())

==================================================
COLUMN: quantity
Q1: 1.0
Q3: 3.0
IQR: 2.0
Lower Bound: -2.0
Upper Bound: 6.0
Potential Outliers: 42

==================================================
COLUMN: unit_price
Q1: 570.0
Q3: 3150.0
IQR: 2580.0
Lower Bound: -3300.0
Upper Bound: 7020.0
Potential Outliers: 3068

==================================================
COLUMN: discount_percentage
Q1: 1.5
Q3: 21.5
IQR: 20.0
Lower Bound: -28.5
Upper Bound: 51.5
Potential Outliers: 0

==================================================
COLUMN: item_revenue
Q1: 900.675
Q3: 6362.0
IQR: 5461.325
Lower Bound: -7291.312499999999
Upper Bound: 14553.9875
Potential Outliers: 2702

==================================================
COLUMN: item_cost
Q1: 719.53
Q3: 5246.16
IQR: 4526.63
Lower Bound: -6070.415
Upper Bound: 12036.105
Potential Outliers: 2740

==================================================
COLUMN: profit
Q1: 62.32
Q3: 1022.64
IQR: 960.3199999999999
Lower Bound: -1378.16
Upper Bound: 2463.12
Potential Outliers: 3060

In [19]:
print("Original shape:", df_original.shape)
print("Current shape:", df.shape)

print("\nRows removed:",
      df_original.shape[0] - df.shape[0])

print("Columns removed:",
      df_original.shape[1] - df.shape[1])

print("\nCurrent duplicate rows:",
      df.duplicated().sum())

print("Current total missing values:",
      df.isna().sum().sum())

Original shape: (20000, 9)
Current shape: (20000, 9)

Rows removed: 0
Columns removed: 0

Current duplicate rows: 0
Current total missing values: 0

In [20]:
df.to_csv("order_items_cleaned.csv", index=False)

print("order_items_cleaned.csv created successfully")

order_items_cleaned.csv created successfully

In [21]:
import os

print("File exists:", os.path.exists("order_items_cleaned.csv"))
print("File size:", os.path.getsize("order_items_cleaned.csv"), "bytes")

File exists: True
File size: 1360163 bytes